Feature/#457 need to show read only paths to folder locations in settings
typerefinery-ai/typerefinery pull request #489
Opened 2023-05-03 16:40 UTC by Rahul139-stack

This Pr includes:

- Able to get Install app path
- Able to app logs path.
- 
![image](https://user-images.githubusercontent.com/81350384/235982852-8d58252d-309c-427d-a3ce-f2b41989bfbf.png)

2023-05-04 11:43 UTC, Harikarthyk requested changes
Can you please update the UI 

Input can be disabled as default.
Can have some margins Font weight can be reduced and size increased. 

 Copy Icon can be added new the title, it can have the app primary color.

2023-05-04 11:43 UTC, Harikarthyk commented on electron/app/main/index.ts
> +      const appPath = app.getPath("appData") + `\\TypeRefinery`
will this path which you have mentioned will work for all the OS ?

2023-05-05 05:01 UTC, Rahul139-stack commented
> Can you please update the UI?
> 
> Input can be disabled by default. Can have some margins The font weight can be reduced and the size increased.
> 
> A copy icon can be added to the title; it can have the app's primary colour.
> 
> Along with this, please provide an option to open the file by clicking a button.

Updated the UI as required

2023-05-05 05:05 UTC, Harikarthyk commented
Please add the Preview of how it looks.

2023-05-05 05:06 UTC, Rahul139-stack commented
> Please add the Preview of how it looks.

![image](https://user-images.githubusercontent.com/81350384/236381220-6e980493-6286-4c45-a947-87852073c788.png)

2023-05-05 06:04 UTC, Harikarthyk approved these changes

2023-05-08 02:35 UTC, merged